#!/usr/bin/env node
/**
 * build-catalog.mjs
 *
 * Turns the editable raw product rows in scripts/sources/*.json into the bundled,
 * type-safe seed catalog at src/services/intelligence/seed.ts. This is the
 * "update the repository" path: add or edit rows under scripts/sources/, run
 * `npm run build:catalog`, and commit the regenerated seed.ts.
 *
 * Match keys are intentionally NOT computed here — the app derives them at load
 * time from brand/name/quantity (intelligence/normalize.ts) so there is exactly
 * one source of truth and no drift between tooling and runtime.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCES_DIR = join(__dirname, 'sources');
const OUT_FILE = join(__dirname, '..', 'src', 'services', 'intelligence', 'seed.ts');

// Mirror of intelligence/api deriveSubCategory — keyword → scoring sub-category.
const SUBCAT_MATCHERS = [
    [/biscuit/i, 'biscuits'],
    [/cookie/i, 'cookies'],
    [/cereal|muesli|granola|oats/i, 'cereals'],
    [/breakfast/i, 'breakfast'],
    [/\boils?\b|ghee/i, 'oils'],
    [/soda|cola|carbonated|energy.?drink|soft.?drink/i, 'drinks'],
    [/juice|beverage|tea|coffee|squash/i, 'beverages'],
    [/dairy|milk|yogh?urt|cheese|curd|paneer/i, 'dairy'],
    [/snack|chips|crisps|namkeen|bhujia|wafer|nachos/i, 'snacks'],
];

const deriveSubCategory = (row) => {
    if (row.subCategory) return row.subCategory;
    const hay = `${row.name || ''} ${row.brand || ''}`;
    for (const [re, key] of SUBCAT_MATCHERS) if (re.test(hay)) return key;
    return undefined;
};

const isValid = (row) =>
    row && typeof row.name === 'string' && row.name.trim() &&
    row.nutrition && typeof row.nutrition === 'object';

const dedupeKey = (row) =>
    `${row.barcode || ''}|${(row.brand || '').toLowerCase().trim()}|${row.name.toLowerCase().trim()}`;

const main = async () => {
    let files = [];
    try {
        files = (await readdir(SOURCES_DIR)).filter(f => f.endsWith('.json')).sort();
    } catch {
        console.error(`No sources directory at ${SOURCES_DIR}`);
        process.exit(1);
    }

    const rows = [];
    let skipped = 0;
    for (const file of files) {
        const text = await readFile(join(SOURCES_DIR, file), 'utf8');
        let parsed;
        try {
            parsed = JSON.parse(text);
        } catch (e) {
            console.error(`✗ ${file}: invalid JSON — ${e.message}`);
            process.exit(1);
        }
        const arr = Array.isArray(parsed) ? parsed : [parsed];
        for (const row of arr) {
            if (!isValid(row)) { skipped++; continue; }
            rows.push({ ...row, subCategory: deriveSubCategory(row) });
        }
    }

    // Dedupe (last write wins) and sort for a stable, reviewable diff.
    const byKey = new Map();
    for (const row of rows) byKey.set(dedupeKey(row), row);
    const out = [...byKey.values()].sort((a, b) =>
        (a.subCategory || '').localeCompare(b.subCategory || '') ||
        (a.brand || '').localeCompare(b.brand || '') ||
        a.name.localeCompare(b.name));

    const body = out.map(r => '    ' + JSON.stringify(r)).join(',\n');
    const file =
`/**
 * intelligence/seed.ts
 *
 * AUTO-GENERATED by scripts/build-catalog.mjs from scripts/sources/*.json.
 * Do not edit by hand — edit the source rows and run \`npm run build:catalog\`.
 *
 * The bundled base catalog. Values are per-100g, drawn from public pack labels /
 * Open Food Facts and are intended as a SEED — the live Open Food Facts lookup and
 * the self-healing learned cache are the up-to-date sources at runtime.
 */

import { RawProduct } from './types';

export const SEED: RawProduct[] = [
${body}
];
`;

    await writeFile(OUT_FILE, file, 'utf8');
    console.log(`✓ Wrote ${out.length} products to ${OUT_FILE}` + (skipped ? ` (${skipped} invalid rows skipped)` : ''));
};

main().catch(e => { console.error(e); process.exit(1); });
